### ISSUE TITLE
New upstream 0.8.3

### ISSUE THREAD

**Issue by irl** [fpytloun/debian-khal#1]
Hi,

There's a new upstream available, 0.8.3.

Thanks,

**Comment by fpytloun** [comment]
Hello,

thank you for pinging me.
I have just pushed update into papt/khal where packaging is stored now and just waiting for upload to Debian:
https://anonscm.debian.org/viewvc/python-apps/packages/khal/trunk/

**Comment by irl** [comment]
If you upload to mentors.debian.net and give me the URL, I'll upload it now.

(I have no idea how the PAPT subversion thingy works)
